{
 "title": "RebootMadDevice - Stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "DeviceName",
    "label": "DeviceName",
    "query": {
     "query": "query_result(rmd_metric_device_info)"
    }
   },
   {
    "name": "InstanceName",
    "label": "InstanceName",
    "query": {
     "query": "query_result(rmd_build_version_info)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device Configuration",
   "type": "table",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rmd_metric_device_info{instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RMD Clients and Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "rmd_build_version_info{instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_script_cycle_info{instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Devices",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*100/$B", "type": "math" }
   ]
  },
  {
   "title": "Rebooting Devices",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "$C*100/$A", "type": "math" }
   ]
  },
  {
   "title": "Offline Devices",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expression": "$D*100/$A", "type": "math" }
   ]
  },
  {
   "title": "Online Devices",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A*100/$B", "type": "math" }
   ]
  },
  {
   "title": "Reboots per device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(device) (rmd_metric_device_reboot_count{device=~\"$DeviceName\", instance=~\"$InstanceName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reboots overall",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 18 },
   "targets": [
    {
     "expr": "sum(rmd_metric_device_reboot_count{device=~\"$DeviceName\", instance=~\"$InstanceName\"})",
     "legendFormat": "overall"
    }
   ]
  },
  {
   "title": "RMD Device Status",
   "type": "table",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rmd_metric_device_last_seen{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_last_reboot_time{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_last_reboot_forced_time{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_reboot_count{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_webhook_id{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 27 },
   "targets": [
    {
     "expr": "rmd_metric_device_last_seen{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_last_reboot_time{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_last_reboot_forced_time{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_reboot_count{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_status{device=~\"$DeviceName\", instance=~\"$InstanceName\"} == 2"
    }
   ]
  },
  {
   "title": "Rebooting Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 35 },
   "targets": [
    {
     "expr": "rmd_metric_device_last_seen{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_last_reboot_time{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_last_reboot_forced_time{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_reboot_count{device=~\"$DeviceName\", instance=~\"$InstanceName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rmd_metric_device_status{device=~\"$DeviceName\", instance=~\"$InstanceName\"} == 1"
    }
   ]
  }
 ]
}